version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: constellation_postgres
    environment:
      POSTGRES_DB: constellation_db
      POSTGRES_USER: constellation_user
      POSTGRES_PASSWORD: constellation_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: constellation_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: constellation_bot
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: